### ISSUE TITLE
Plugin doesn't work with Velocity 3.4.0

### ISSUE THREAD

**Issue by NoltoxGit** [Smudgge/Leaf#114]
`Leaf Version:`
Leaf 5.2.2

**Description of the Bug**
When i update to velocity 3.4.0, the plugin crash on startup.

**Console Errors**
```
[18:18:39 INFO]: Booting up Velocity 3.4.0-SNAPSHOT (git-e12d471b)...
[18:18:39 INFO]: Connections will use epoll channels, libdeflate (Linux x86_64) compression, OpenSSL 3.x.x (Linux x86_64) ciphers
[18:18:39 INFO]: Loading localizations...
[18:18:39 INFO]: Loading plugins...
[18:18:40 INFO]: Loaded plugin ajqueue 2.7.0-b162 by ajgeiss0702
[18:18:40 INFO]: Loaded plugin azlink 1.3.7 by Azuriom Team
[18:18:40 INFO]: Loaded plugin commandforward 0.5.0 by games647, https://github.com/games647/CommandForward/graphs/contributors
[18:18:40 INFO]: [LOG] [SQLiteDatabase] Connected to the database successfully.
[18:18:40 INFO]: Loaded plugin leaf 5.2.2 by Smudge
[18:18:40 INFO]: Loaded plugin litebans 2.15.1 by Ruan
[18:18:40 INFO]: Loaded plugin luckperms 5.4.141 by Luck
[18:18:40 INFO]: Loaded plugin maintenance 4.3.0 by kennytv
[18:18:40 INFO]: Loaded plugin maintenanceaddon 2.0.6 by kennytv
[18:18:40 INFO]: Loaded plugin novpn 2.0.0-beta by besuper
[18:18:40 INFO] [packetevents]: Plugin started
[18:18:40 INFO]: Loaded plugin packetevents 2.5.0+dc015dc45-SNAPSHOT by retrooper
[18:18:40 INFO] [pl-hide-pro]: Loading library caffeine
[18:18:40 INFO]: Loaded plugin pl-hide-pro 2.10.4 by Nononitas
[18:18:40 INFO]: Loaded plugin plan 5.6 build 2883 by AuroraLS3
[18:18:40 INFO]: Loaded plugin premiumvanish 2.9.14 by MyzelYam
[18:18:40 INFO]: Loaded plugin signedvelocity 1.2.4 by 4drian3d
[18:18:40 INFO]: Loaded plugin ultrastaffchatpro 2.0.18 by Joshua Sing
[18:18:40 INFO]: Loaded 16 plugins
[18:18:40 INFO]: __
[18:18:40 INFO]: | |__) LuckPerms v5.4.141
[18:18:40 INFO]: |___ | Running on Velocity - Velocity
[18:18:40 INFO]:
[18:18:40 INFO] [luckperms]: Loading configuration...
[18:18:40 INFO] [luckperms]: Loading storage provider... [MARIADB]
[18:18:40 INFO] [me.lucko.luckperms.lib.hikari.HikariDataSource]: luckperms-hikari - Starting...
[18:18:40 INFO] [me.lucko.luckperms.lib.hikari.HikariDataSource]: luckperms-hikari - Start completed.
[18:18:40 INFO] [luckperms]: Loading messaging service... [SQL]
[18:18:40 INFO] [luckperms]: Loading internal permission managers...
[18:18:40 INFO] [luckperms]: Performing initial data load...
[18:18:40 INFO] [luckperms]: Successfully enabled. (took 524ms)
[18:18:40 INFO] [azlink]: Starting HTTP server
[18:18:40 INFO] [azlink]: HTTP server started on /[0:0:0:0:0:0:0:0]:19132
[18:18:40 INFO] [leaf]:
[18:18:40 INFO] [leaf]: __ ______ ______ ______
[18:18:40 INFO] [leaf]: /\ \ /\ ___\ /\ __ \ /\ ___\
[18:18:40 INFO] [leaf]: \ \ \____ \ \ __\ \ \ __ \ \ \ __\
[18:18:40 INFO] [leaf]: \ \_____\ \ \_____\ \ \_\ \_\ \ \_\
[18:18:40 INFO] [leaf]: \/_____/ \/_____/ \/_/\/_/ \/_/
[18:18:40 INFO] [leaf]:
[18:18:40 INFO] [leaf]: By Smudge Version 5.2.2
[18:18:40 INFO] [leaf]:
[18:18:40 INFO] [leaf]: ● Enabled Discord Support ~10mib
[18:18:40 INFO] [leaf]: ● Enabled Database Support ~10mib
[18:18:40 INFO] [leaf]:
[18:18:40 INFO] [leaf]: [Placeholders] Registered placeholder : player
[18:18:40 INFO] [leaf]: [Placeholders] Registered placeholder : ping
[18:18:40 INFO] [leaf]: [Placeholders] Registered placeholder : uuid
[18:18:40 INFO] [leaf]: [Placeholders] Registered placeholder : server
[18:18:40 INFO] [leaf]: [Placeholders] Registered placeholder : vanished
[18:18:40 INFO] [leaf]: [Placeholders] Registered placeholder : version
[18:18:40 INFO] [leaf]: [Placeholders] Registered placeholder : message
[18:18:40 INFO] [leaf]: [Placeholders] Registered placeholder : error_colour
[18:18:40 INFO] [leaf]: [Placeholders] Registered placeholder : vanish_colour
[18:18:40 INFO] [leaf]: [Placeholders] Registered placeholder : server_formatted
[18:18:40 INFO] [leaf]: [Placeholders] Registered placeholder : rank_colour
[18:18:40 INFO] [leaf]: [Placeholders] Registered placeholder : theme_material
[18:18:40 INFO] [leaf]: [Placeholders] Registered placeholder : theme
[18:18:40 INFO] [leaf]: [Events] Registered event : player_joined_the_server
[18:18:40 INFO] [leaf]: [Events] Registered event : player_switched_servers
[18:18:40 INFO] [leaf]: [Events] Registered event : player_left_network
[18:18:40 INFO] [leaf]: Discord bot disabled.
[18:18:40 INFO] [leaf]: [Commands] Enabling command : leafreload
[18:18:40 INFO] [leaf]: [Commands] Enabling command : checkplayer
[18:18:40 INFO] [leaf]: [Commands] Enabling command : report
[18:18:40 INFO] [leaf]: [Commands] friends is disabled in the configuration file.
[18:18:40 INFO] [leaf]: [Commands] Enabling command : leafmenu
[18:18:40 INFO] [leaf]: [Commands] leafchat is disabled in the configuration file.
[18:18:40 INFO] [leaf]: [Commands] staff_chat is disabled in the configuration file.
[18:18:40 INFO] [leaf]: [Commands] builder_chat is disabled in the configuration file.
[18:18:40 INFO] [leaf]: [Commands] modo_chat is disabled in the configuration file.
[18:18:40 INFO] [leaf]: [Commands] admin_chat is disabled in the configuration file.
[18:18:40 INFO] [leaf]: [Commands] staff_list is disabled in the configuration file.
[18:18:40 INFO] [leaf]: [Dependencies] Could not find optional dependency Protocolize
[18:18:40 INFO] [leaf]: [Dependencies] Inventories and sounds will be disabled.
[18:18:40 INFO] [leaf]: Protocolize : https://www.spigotmc.org/resources/protocolize-protocollib-for-bungeecord-waterfall-velocity.63778/
[18:18:40 INFO] [leaf]: [Dependencies] Could not find optional dependency Mini Placeholders
[18:18:40 INFO] [leaf]: [Dependencies] This optional plugin lets you use mini placeholders, not to be confused with leaf placeholders.
[18:18:40 INFO] [leaf]: Mini Placeholders : https://modrinth.com/plugin/miniplaceholders
[18:18:40 ERROR]: Couldn't pass ProxyInitializeEvent to leaf 5.2.2
java.lang.RuntimeException: java.lang.NoClassDefFoundError: com/velocitypowered/proxy/protocol/packet/PluginMessage
at com.github.smuddgge.leaf.brand.HooksInitializer.init(HooksInitializer.java:64) ~[?:?]
at com.github.smuddgge.leaf.Leaf.onProxyInitialization(Leaf.java:176) ~[?:?]
at com.github.smuddgge.leaf.Lmbda$14.execute(Unknown Source) ~[?:?]
at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-proxy-3.4.0-1062-all.jar:3.4.0-SNAPSHOT (git-e12d471b)]
at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:526) ~[velocity-proxy-3.4.0-1062-all.jar:3.4.0-SNAPSHOT (git-e12d471b)]
at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:515) ~[velocity-proxy-3.4.0-1062-all.jar:3.4.0-SNAPSHOT (git-e12d471b)]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
Caused by: java.lang.NoClassDefFoundError: com/velocitypowered/proxy/protocol/packet/PluginMessage
at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1023) ~[?:?]
at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[?:?]
at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[?:?]
at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?]
at java.base/java.security.AccessController.doPrivileged(AccessController.java:714) ~[?:?]
at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?]
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:70) ~[velocity-proxy-3.4.0-1062-all.jar:3.4.0-SNAPSHOT (git-e12d471b)]
at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity-proxy-3.4.0-1062-all.jar:3.4.0-SNAPSHOT (git-e12d471b)]
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
at com.github.smuddgge.leaf.brand.HooksInitializer.init(HooksInitializer.java:36) ~[?:?]
... 8 more
Caused by: java.lang.ClassNotFoundException: com.velocitypowered.proxy.protocol.packet.PluginMessage
at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[velocity-proxy-3.4.0-1062-all.jar:3.4.0-SNAPSHOT (git-e12d471b)]
at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity-proxy-3.4.0-1062-all.jar:3.4.0-SNAPSHOT (git-e12d471b)]
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1023) ~[?:?]
at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[?:?]
at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[?:?]
at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?]
at java.base/java.security.AccessController.doPrivileged(AccessController.java:714) ~[?:?]
at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?]
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:70) ~[velocity-proxy-3.4.0-1062-all.jar:3.4.0-SNAPSHOT (git-e12d471b)]
at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity-proxy-3.4.0-1062-all.jar:3.4.0-SNAPSHOT (git-e12d471b)]
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
at com.github.smuddgge.leaf.brand.HooksInitializer.init(HooksInitializer.java:36) ~[?:?]
... 8 more
[18:18:41 INFO] [azlink]: Successfully connected to https://heavencube.fr
[18:18:41 INFO] [litebans]: Using system locale (en)
[18:18:41 INFO] [litebans]: Loaded 0 templates from templates.yml!
[18:18:41 INFO] [litebans]: Loading SQL driver: mariadb 3.1.2 (org.mariadb.jdbc.Driver)
[18:18:41 INFO] [litebans]: Connecting to database...
[18:18:41 INFO] [litebans]: litebans-pool - Starting...
[18:18:41 INFO] [litebans]: litebans-pool - Start completed.
[18:18:41 INFO] [litebans]: Connected to MariaDB database successfully (32 ms).
[18:18:41 INFO] [litebans]: Database connection fully initialized (36.3 ms).
[18:18:41 INFO] [litebans]: v2.15.1 enabled. Startup took 245 ms.
[18:18:41 INFO] [maintenance]: Updating config to the latest version...
[18:18:41 INFO] [maintenance]: Done! Updated config!
[18:18:41 INFO] [novpn]: [DEBUG] Handshake response body :c57acbc76ca6142efc535b1b3a63dcb0c327607bd2a81dd9ae1b735029963484
[18:18:41 INFO] [novpn]: Handshake with NoVPN API servers success
[18:18:41 INFO] [novpn]: Cache loaded 2
[18:18:41 INFO] [packetevents]: Injecting packetevents...
[18:18:41 WARN]: The server channel initializer has been replaced by java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[18:18:41 INFO]: Checking for updates, please wait...
[18:18:41 WARN] [pl-hide-pro]: -----------------------------------------------------------------------
[18:18:41 WARN] [pl-hide-pro]: Couldn't detect the Velocity build number.
[18:18:41 WARN] [pl-hide-pro]: Please make sure you are using an up to date version!
[18:18:41 WARN] [pl-hide-pro]: -----------------------------------------------------------------------
[18:18:41 INFO] [plan]: §2
[18:18:41 INFO] [plan]: §2 ██▌
[18:18:41 INFO] [plan]: §2 ██▌ ██▌
[18:18:41 INFO] [plan]: §2 ██▌██▌██▌██▌ §2Player Analytics
[18:18:41 INFO] [plan]: §2 ██▌██▌██▌██▌ §fv5.6 build 2883
[18:18:41 INFO] [plan]: §2
[18:18:41 INFO] [plan]: Config: Removed Customized_files.Plan
[18:18:41 INFO]: You are running a development build of PacketEvents. Your build: (§b2.5.0+dc015dc45-SNAPSHOT§f) | Latest release: (§32.4.0§f)
[18:18:41 INFO] [plan]: Locale: 'Custom' by
[18:18:41 INFO] [plan]: Downloading MySQL Driver, this may take a while...
[18:18:41 INFO] [plan]: Vous utilisez la dernière version.
[18:18:41 INFO] [plan]: Database: Making sure schema is up to date..
[18:18:41 INFO] [plan]: Connexion à la base de données établie. (MySQL)
[18:18:41 INFO] [plan]: Serveur Web : Fichier KeyStore du certificat introuvable : plugins/plan/Cert.jks
[18:18:41 INFO] [plan]: Serveur Web : Aucun certificat -> Utilisation du serveur HTTP pour la visualisation.
[18:18:41 INFO] [plan]: Serveur Web : Authentification utilisateur désactivée ! (Non sécurisée avec HTTP)
[18:18:41 INFO] [plan]: Le serveur Web communique à travers le port 25566 ( http://94.231.36.112:25566 ).
[18:18:41 INFO] [plan]: Loading server identifying information
[18:18:41 INFO] [plan]: Registered extension: Litebans
[18:18:41 INFO] [plan]: Registered extension: LuckPerms
[18:18:41 INFO] [plan]: Plan a été activé.
[18:18:41 INFO] [plan]: Tous les correctifs pour la base de données ont été appliqués avec succès.
[18:18:41 INFO] [de.myzelyam.libraries.com.zaxxer.hikari.HikariDataSource]: PremiumVanish Database - Starting...
[18:18:42 INFO] [de.myzelyam.libraries.com.zaxxer.hikari.HikariDataSource]: PremiumVanish Database - Start completed.
[18:18:42 INFO] [signedvelocity]: Starting SignedVelocity
[18:18:42 INFO]:
[18:18:42 INFO]: __ ______________
[18:18:42 INFO]: / / / / __/ ___/ _ \ UltraStaffChatPro v2.0.18
[18:18:42 INFO]: / /_/ /\ \/ /__/ ___/ Running on Velocity
[18:18:42 INFO]: \____/___/\___/_/
[18:18:42 INFO]:
[18:18:42 INFO] [ultrastaffchatpro]: Successfully started, took 66 ms
[18:18:42 INFO] [ultrastaffchatpro]: Successfully loaded dependencies, took about 1 ms.
[18:18:42 INFO]: Listening on /[0:0:0:0:0:0:0:0]:25565
[18:18:42 INFO]: Listening for GS4 query on /[0:0:0:0:0:0:0:0]:25567
[18:18:42 INFO]: Done (2.64s)!
[18:18:42 INFO] [ajqueue]: You are up to date! (2.7.0)
```

**Comment by LewisLosa** [comment]
i have same issue pls update it
